name: Unit tests checks

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 'run tests'
      uses: actions/setup-node@v1
      with:
        node-version: 20
    - run: npm install
    - run: npm run test

  lint:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 'run linter'
      uses: actions/setup-node@v1
      with:
        node-version: 20
    - run: npm install
    - run: npm run lint

  check-pr-title:
  
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check Title Format
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^(feat|fix|refactor|docs|test):\s\[\w+-\d+\]\s.+$'
          github_token: ${{ secrets.GITHUB_TOKEN }}
